### ISSUE TITLE
noob question

### ISSUE THREAD

**Issue by 8secz-johndpope** [PullRequestInc/go-gpt3#1]
I'm trying to add a key to code and run it

I create and save this file
go run main.go

but it just says 

main.go:8:2: found packages gpt3 (client_options.go) and main (main.go) in /Users/johndpope/Documents/mlWorkspace/go-gpt3

I try importing 
go get -u github.com/PullRequestInc/go-gpt3

it fails 
can't load package: package github.com/PullRequestInc/go-gpt3: found packages gpt3 (client_options.go) and main (main.go) in /Users/johndpope/Documents/mlWorkspace/go-gpt3

```main.go

package main

import (
	"context"
	"log"
	"os"

	"github.com/PullRequestInc/go-gpt3"
	"github.com/joho/godotenv"
)

func main() {
	godotenv.Load()

	apiKey := os.Getenv("key")
	if apiKey == "" {
		log.Fatalln("Missing API KEY")
	}

	ctx := context.Background()
	client := gpt3.NewClient(apiKey)

	resp, err := client.Completion(ctx, gpt3.CompletionRequest{
		Prompt: []string{
			"1\n2\n3\n4",
		},
		MaxTokens: gpt3.IntPtr(10),
	})
	if err != nil {
		log.Fatalln(err)
	}
	log.Printf("hellooo%+v\n", resp)

	resp, err = client.Completion(ctx, gpt3.CompletionRequest{
		Prompt: []string{
			"go:golang\npy:python\njs:",
		},
		Stop: []string{"\n"},
	})
	if err != nil {
		log.Fatalln(err)
	}
	log.Printf("%+v\n", resp)
}
```

**Comment by 8secz-johndpope** [comment]
might be nice to have something to spoon feed people 
https://github.com/minimaxir/gpt-3-experiments

this repo I got up and running really quickly within 30 seconds.

**Comment by tylermann** [comment]
ah interesting I haven't seen this exact error, but I think this is maybe because you need to be working within a go module. you can initialize a go module in your folder with something like `go mod init github.com/8secz-johndpope/go-gpt-test`.

Or otherwise you can try just cloning this repo because I actually have a test main.go within it that you can run if you just want to get going as fast as possible. As long as you have a version of Go that supports modules (1.12+) this should work:

```
git clone https://github.com/PullRequestInc/go-gpt3.git
cd go-gpt3
go run cmd/test/main.go
```

that should build/run the script here: https://github.com/PullRequestInc/go-gpt3/blob/main/cmd/test/main.go and since you are running with this repo it already has the `go mod init` above setup which creates the go.mod and go.sum files.

you will still need to add a `.env` file with API_KEY as mentioned in the docs otherwise you will get `Missing API KEY` error when running. let me know if that helps, but I was able to do this exact process just now in a fresh go docker container and it worked so should hopefully work for you.

**Comment by 8secz-johndpope** [comment]
I'd like to use go - but getting further with python 
https://github.com/johndpope/gpt3-persona-bot

thanks for your help / gonna close this.
