### ISSUE TITLE
Unrecognized request argument supplied: engine_id

### ISSUE THREAD

**Issue by colourdelete** [PullRequestInc/go-gpt3#2]
Hello, thanks for making this!

When making a completion request, this error is returned:

```
[400:invalid_request_error] Unrecognized request argument supplied: engine_id
```

I think the code should ignore `CompletionRequest.EngineID` since the engine ID would be controlled by the `engine` argument when present.

EDIT: Since this would change behavior, there would need to be a new version.

**Comment by tylermann** [comment]
I think you're right. It doesn't actually look like `EngineID` is used anymore. I think this may just be left over from a previous iteration. For now I would just set the engine either on the base client or use `CompletionWithEngine`, etc. I can remove the fields though for the next version so that its not as confusing.

**Comment by tylermann** [comment]
Just pushed a new version 1.1.3 for this. the minor version should be fine here just because if anyone was using that id previously it wouldn't have been working. Let me know if you have any more issues, thanks!
